apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-api-deployment
spec:
  selector:
    matchLabels:
      app: fake-api
  replicas: 2
  template:
    metadata:
      labels:
        app: fake-api
    spec:
      containers:
      - name: fake-api
        image: fake-api:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Never